sonata_admin:
    title:          'SMART BOOSTER'
    title_logo:     '/images/logo/smartbooster-logo.svg'
    options:
        title_mode: 'single_image'

    security:
        handler: sonata.admin.security.handler.noop

    templates:
        layout: admin/layout.html.twig
        user_block: "@SmartAuthentication/block/user.html.twig"

    extensions:
        admin.extension.action_impersonate:
            instanceof:
                - App\Entity\User\Administrator
        admin.extension.action_send_account_creation_email:
            instanceof:
                - App\Entity\User\Administrator

    dashboard:
        groups:
            users:
                label: dashboard.label_users
                label_catalogue: admin
                icon: '<i class="fa fa-users"></i>'
                items:
                    - admin.user.administrator
            documentations:
                label: dashboard.label_documentations
                label_catalogue: admin
                icon: '<i class="fa fa-book"></i>'
                items:
                    - route: documentation_email
                      label: dashboard.label_documentation_email

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    admin.extension.action_impersonate:
        class: Smart\SonataBundle\Admin\Extension\ActionExtension
        arguments:
            - impersonate

    admin.user.administrator:
        class: App\Admin\User\AdministratorAdmin
        arguments:
            - ~
            - App\Entity\User\Administrator
            - App\Controller\Admin\CRUD\User\AdministratorController
        tags:
            - { name: sonata.admin, manager_type: orm, label: dashboard.label_administrator }
