version: "3"

services:
  php:
    container_name: ${APPLICATION}-docker-php
    image: smartbooster/php-fpm:builder
    env_file:
       - .env
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - ./var/log/php/:/var/www/var/logs
  nginx:
    build:
      context: '.docker/nginx'
      args:
        HOST_USER: ${HOST_USER}
        HOST_GROUP: ${HOST_GROUP}
    container_name: ${APPLICATION}-docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/log/nginx/:/var/log/nginx
  mysql:
    image: mysql:5.7
    container_name: ${APPLICATION}-docker-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    hostname: mysql
    volumes:
      - ./var/data/mysql:/var/lib/mysql/:rw

  maildev:
    container_name: ${APPLICATION}-docker-maildev
    image: djfarrelly/maildev
    hostname: maildev
    ports:
      - "1080:80"
