admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    host:     "admin.%domain%"

smart_sonata:
    resource: "@SmartSonataBundle/config/routing.yaml"
    host:     "admin.%domain%"

_sonata_admin:
    resource: .
    type: sonata_admin

_admin:
    resource: admin
    host:     "admin.%domain%"
    type:     directory

admin_dashboard:
    path:    /
    host:     "admin.%domain%"
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'sonata_admin_dashboard'

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'sonata_admin_dashboard'
