admin_security_login_form:
    path:    /login
    methods: [GET]
    defaults:
        _controller: App\Controller\Admin\SecurityController:login

admin_security_login_check:
    path:    /login_check
    methods: [POST]

admin_security_logout:
    path:    /logout
    methods: [GET]

admin_security_forgot_password:
    path:    /forgot_password
    methods: [GET, POST]
    defaults:
        _controller: App\Controller\Admin\SecurityController:forgotPassword

admin_security_reset_password:
    path:    /reset_password
    methods: [GET, POST]
    defaults:
        _controller: App\Controller\Admin\SecurityController:resetPassword

admin_security_profile:
    path:    /profile
    methods: [GET, POST]
    defaults:
        _controller: App\Controller\Admin\SecurityController:profile